import './globals.css'
import { Catamaran } from 'next/font/google'

const catamaran = Catamaran({
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body className={catamaran.className}>{children}</body>
    </html>
  )
}
